import type { TripPlan } from "../types/trip-plan";

export const dummyTripPlans: TripPlan[] = [
  {
    id: "zagreb-ljubljana-graz",
    title: "Zagreb, Ljubljana & Graz",
    summary:
      "A relaxed four-day loop through three compact Central European cities.",
    startDate: "2026-09-12",
    endDate: "2026-09-15",
    travellerCount: 3,
    distanceKm: 520,
    stops: [
      {
        id: "zagreb-start",
        city: "Zagreb",
        country: "Croatia",
        date: "2026-09-12",
        nights: 0,
        note: "Morning departure after coffee near the city centre.",
      },
      {
        id: "ljubljana",
        city: "Ljubljana",
        country: "Slovenia",
        date: "2026-09-12",
        nights: 2,
        note: "Old Town walk, riverside dinner and a day trip to Lake Bled.",
        accommodation: {
          name: "Trnovo Riverside Apartment",
          nights: 2,
          amountCents: 22000,
          parkingIncluded: true,
        },
      },
      {
        id: "graz",
        city: "Graz",
        country: "Austria",
        date: "2026-09-14",
        nights: 1,
        note: "Schlossberg, the historic centre and an evening food market.",
        accommodation: {
          name: "Lend District Apartment",
          nights: 1,
          amountCents: 14000,
          parkingIncluded: false,
        },
      },
      {
        id: "zagreb-return",
        city: "Zagreb",
        country: "Croatia",
        date: "2026-09-15",
        nights: 0,
        note: "Afternoon return with a short rest stop near Maribor.",
      },
    ],
    costs: [
      { category: "accommodation", label: "Apartments", amountCents: 36000 },
      { category: "fuel", label: "Fuel", amountCents: 7200 },
      { category: "tolls", label: "Tolls & vignettes", amountCents: 3800 },
      { category: "parking", label: "Parking", amountCents: 4200 },
      { category: "food", label: "Food & coffee", amountCents: 21000 },
      { category: "activities", label: "Activities", amountCents: 9000 },
    ],
  },
  {
    id: "zagreb-istria-coast",
    title: "Zagreb to the Istrian Coast",
    summary:
      "Hilltop towns, Adriatic sunsets and a coastal drive through Rovinj and Pula.",
    startDate: "2026-06-18",
    endDate: "2026-06-21",
    travellerCount: 2,
    distanceKm: 610,
    stops: [
      {
        id: "zagreb-istria-start",
        city: "Zagreb",
        country: "Croatia",
        date: "2026-06-18",
        nights: 0,
        note: "Early start toward the coast with a break above Kvarner Bay.",
      },
      {
        id: "rovinj",
        city: "Rovinj",
        country: "Croatia",
        date: "2026-06-18",
        nights: 2,
        note: "Old Town lanes, Punta Corrente and an evening by the harbour.",
        accommodation: {
          name: "Rovinj Garden Studio",
          nights: 2,
          amountCents: 26000,
          parkingIncluded: true,
        },
      },
      {
        id: "pula",
        city: "Pula",
        country: "Croatia",
        date: "2026-06-20",
        nights: 1,
        note: "Arena visit, Cape Kamenjak and a final seafood dinner.",
        accommodation: {
          name: "Arena Courtyard Apartment",
          nights: 1,
          amountCents: 12500,
          parkingIncluded: false,
        },
      },
      {
        id: "zagreb-istria-return",
        city: "Zagreb",
        country: "Croatia",
        date: "2026-06-21",
        nights: 0,
        note: "Return after breakfast via the A6 and A1.",
      },
    ],
    costs: [
      { category: "accommodation", label: "Apartments", amountCents: 38500 },
      { category: "fuel", label: "Fuel", amountCents: 8400 },
      { category: "tolls", label: "Tolls", amountCents: 5200 },
      { category: "parking", label: "Parking", amountCents: 3500 },
      { category: "food", label: "Food & coffee", amountCents: 18500 },
      { category: "activities", label: "Activities", amountCents: 6800 },
    ],
  },
  {
    id: "split-makarska-dubrovnik",
    title: "Split, Makarska & Dubrovnik",
    summary:
      "Five days of coastal roads, old stone towns and swimming stops in the south.",
    startDate: "2026-08-23",
    endDate: "2026-08-27",
    travellerCount: 4,
    distanceKm: 590,
    stops: [
      {
        id: "split",
        city: "Split",
        country: "Croatia",
        date: "2026-08-23",
        nights: 1,
        note: "Diocletian's Palace, Marjan viewpoint and dinner on the Riva.",
        accommodation: {
          name: "Varos Stone House",
          nights: 1,
          amountCents: 18000,
          parkingIncluded: false,
        },
      },
      {
        id: "makarska",
        city: "Makarska",
        country: "Croatia",
        date: "2026-08-24",
        nights: 1,
        note: "Beach morning and a sunset drive below Biokovo.",
        accommodation: {
          name: "Makarska Promenade Apartment",
          nights: 1,
          amountCents: 17000,
          parkingIncluded: true,
        },
      },
      {
        id: "dubrovnik",
        city: "Dubrovnik",
        country: "Croatia",
        date: "2026-08-25",
        nights: 2,
        note: "City walls, Lokrum and a final dinner overlooking the harbour.",
        accommodation: {
          name: "Lapad Bay Apartment",
          nights: 2,
          amountCents: 36000,
          parkingIncluded: true,
        },
      },
    ],
    costs: [
      { category: "accommodation", label: "Apartments", amountCents: 71000 },
      { category: "fuel", label: "Fuel", amountCents: 8200 },
      { category: "tolls", label: "Tolls", amountCents: 900 },
      { category: "parking", label: "Parking", amountCents: 5500 },
      { category: "food", label: "Food & coffee", amountCents: 28500 },
      { category: "activities", label: "Activities", amountCents: 13200 },
    ],
  },
];
